import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
// PGlite is real embedded Postgres; the auth/storage scaffolding stands in for Supabase-owned schemas.
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');
test('migration, RLS, private address, photo limits and lifecycle',async()=>{
 const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
 create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;
 create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;
 grant usage on schema public,storage to anon,authenticated,service_role;grant select,insert,update,delete on storage.objects to anon,authenticated;
 `);
 await db.exec(await readFile(new URL('../supabase/migrations/001_apb.sql',import.meta.url),'utf8'));
 const owner='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',outsider='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
 await db.exec(`insert into auth.users values('${owner}'),('${outsider}');insert into public.admin_users values('${owner}');update business_settings set address='Private test address';`);
 await db.exec("set role anon;select set_config('request.jwt.claim.sub','',false);");assert.equal((await db.query('select count(*)::int n from services')).rows[0].n,5);
 assert.equal((await db.query('select address from public_business_settings')).rows[0].address,'');
 await assert.rejects(db.query('select * from business_settings'),/permission denied/);await assert.rejects(db.query('select * from enquiries'),/permission denied/);
 await assert.rejects(db.query("select reserve_photo('00000000-0000-4000-8000-000000000001')"),/permission denied/);
 await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${outsider}',false);`);
 assert.equal((await db.query('select is_admin() v')).rows[0].v,false);await assert.rejects(db.query("insert into showcase_entries(name) values('Unauthorised')"),/row-level security/);
 assert.equal((await db.query('select * from enquiries')).rows.length,0);
 await assert.rejects(db.query(`insert into admin_users values('${outsider}')`),/permission denied/);
 await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('apb-media','unauthorised.webp')"),/row-level security/);
 await assert.rejects(db.query("insert into enquiries(name,email,telephone,service_name,message,privacy_acknowledged) values('x','x@example.com','07700900123','Test','Test message',true)"),/permission denied/);
 await db.exec(`select set_config('request.jwt.claim.sub','${owner}',false);`);
 assert.equal((await db.query('select is_admin() v')).rows[0].v,true);
 await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('apb-media','bypass.webp')"),/row-level security/);
 const car=(await db.query("insert into showcase_entries(name) values('Test car') returning id")).rows[0].id;
 await assert.rejects(db.query(`update showcase_entries set published=true where id='${car}'`),/at least one/);
 await assert.rejects(db.query(`insert into showcase_images(entry_id,slot,path) values('${car}',1,'invalid')`),/permission denied/);
 await assert.rejects(db.query("update showcase_images set slot=11"),/permission denied/);
 await db.exec('reset role;set role service_role');
 // Promise scheduling also exercises overlapping reservations; the slot constraints are checked below.
 const reservations=await Promise.allSettled(Array.from({length:12},()=>db.query('select * from reserve_photo($1)',[car])));
 assert.equal(reservations.filter(r=>r.status==='fulfilled').length,10);assert.equal(reservations.filter(r=>r.status==='rejected').length,2);
 const photos=(await db.query('select * from showcase_images where entry_id=$1',[car])).rows;assert.equal(new Set(photos.map(p=>p.slot)).size,10);
 await assert.rejects(db.query('insert into showcase_images(entry_id,slot,path) values($1,11,$2)',[car,'bad-range']),/check constraint/);
 await assert.rejects(db.query('insert into showcase_images(entry_id,slot,path) values($1,1,$2)',[car,'duplicate-slot']),/unique constraint/);
 const photo=photos[0];await db.query('select finish_photo($1)',[photo.id]);
 await db.exec(`reset role;insert into storage.objects(bucket_id,name) values('apb-media','${photo.path}');set role authenticated;`);
 await db.query('update showcase_entries set published=true,featured_image_id=$2 where id=$1',[car,photo.id]);
 await db.exec("set role anon;select set_config('request.jwt.claim.sub','',false);");assert.equal((await db.query('select * from showcase_entries')).rows.length,1);assert.equal((await db.query('select * from showcase_images')).rows.length,1);assert.equal((await db.query('select * from storage.objects')).rows.length,1);
 await db.exec('set role service_role');await db.query('select prepare_delete_photo($1)',[photo.id]);
 await db.exec("set role anon;select set_config('request.jwt.claim.sub','',false);");assert.equal((await db.query('select * from showcase_entries')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await db.exec('set role service_role');await db.query('delete from showcase_images where id=$1',[photo.id]);await db.query('select reserve_photo($1)',[car]);
 await db.query('select begin_delete_entry($1)',[car]);await assert.rejects(db.query('select reserve_photo($1)',[car]),/unavailable/);assert.equal((await db.query('select finish_photo($1) v',[photos[1].id])).rows[0].v,false);
 for(let i=1;i<=6;i++)assert.equal((await db.query("select consume_rate_limit('test',900,5) v")).rows[0].v,i<=5);
 await db.close();
});
