import test from 'node:test';
import assert from 'node:assert/strict';
import {validateEnquiry,webpDimensions,limitedBody,checkOrigin} from '../functions/_lib/security.js';
const valid={name:'Test customer',email:'test@example.com',telephone:'07700900123',vehicle:'Test car',message:'Please quote for a detail.',service_id:'00000000-0000-4000-8000-000000000001',privacy_acknowledged:true,token:'test-only'};
test('valid enquiry accepts only the expected fields',()=>{const result=validateEnquiry({...valid,status:'Closed'});assert.equal(result.name,'Test customer');assert.equal(result.status,undefined);assert.equal(result.token,undefined);});
test('rejects malformed, unacknowledged and bot submissions',()=>{for(const patch of [{name:''},{email:'bad'},{telephone:'abcdefg'},{message:'short'},{message:'x'.repeat(5001)},{service_id:'invalid'},{privacy_acknowledged:false},{token:''},{website:'spam'}])assert.throws(()=>validateEnquiry({...valid,...patch}));});
test('origin is exact and fails closed when unconfigured',()=>{const req=new Request('https://apb.example/api/enquiry',{headers:{Origin:'https://apb.example'}});checkOrigin(req,{SITE_URL:'https://apb.example'});assert.throws(()=>checkOrigin(req,{}));assert.throws(()=>checkOrigin(req,{SITE_URL:'https://evil.example'}));assert.throws(()=>checkOrigin(new Request(req.url),{SITE_URL:'https://apb.example'}));});
test('limits streamed bodies even without content-length',async()=>{const req=new Request('https://test.example',{method:'POST',body:'x'.repeat(100)});await assert.rejects(limitedBody(req,99),/too large/);});
function webp(w,h,animated=false){const b=new Uint8Array(48),v=new DataView(b.buffer);b.set(new TextEncoder().encode('RIFF'));v.setUint32(4,40,true);b.set(new TextEncoder().encode('WEBPVP8X'),8);v.setUint32(16,10,true);b[20]=animated?2:0;for(let i=0;i<3;i++){b[24+i]=((w-1)>>(8*i))&255;b[27+i]=((h-1)>>(8*i))&255;}b.set(new TextEncoder().encode('VP8 '),30);v.setUint32(34,10,true);b.set([0x9d,1,0x2a],41);v.setUint16(44,w,true);v.setUint16(46,h,true);return b;}
test('accepts resized WebP dimensions and rejects oversized/animated/original images',()=>{assert.deepEqual(webpDimensions(webp(1920,1080)),{width:1920,height:1080});assert.throws(()=>webpDimensions(webp(7680,4320)));assert.throws(()=>webpDimensions(webp(100,100,true)));assert.throws(()=>webpDimensions(new Uint8Array(100)));});
test('does not trust a misleading extended WebP header',()=>{const b=webp(100,100);new DataView(b.buffer).setUint16(44,7680,true);assert.throws(()=>webpDimensions(b));});
