import PushSettings,{disconnectPush} from './PushSettings';
import {useEffect,useState,type FormEvent,type ReactNode} from 'react';
import type {Session} from '@supabase/supabase-js';
import {db,api} from './client';
import {defaults,type Entry,type Photo,type Service,type Settings,phone,safeSocial} from './data';
import {compressPhoto} from './compress';
type Enquiry={id:string;created_at:string;name:string;email:string;telephone:string;vehicle:string;service_name:string;message:string;status:string;read_at:string|null};
const unwrap=<T,>(r:{data:T;error:{message:string}|null})=>{if(r.error)throw new Error(r.error.message);return r.data;};
function errorText(e:unknown){return e instanceof Error?e.message:'Something went wrong. Please try again.';}
function fields(event:FormEvent<HTMLFormElement>){event.preventDefault();return Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,string>;}
function Check({name,children,checked=false}:{name:string;children:ReactNode;checked?:boolean}){return <label className="check-label"><input type="checkbox" name={name} defaultChecked={checked}/><span>{children}</span></label>;}
function Notice({message}:{message:string}){return message?<p className="notice" role="status">{message}</p>:null;}
export default function Admin(){
 const [session,setSession]=useState<Session|null>(null),[status,setStatus]=useState(db?'checking':'unconfigured'),[recovery,setRecovery]=useState(false);
 useEffect(()=>{document.title='Owner workspace | APB Detailing';const meta=document.createElement('meta');meta.name='robots';meta.content='noindex,nofollow';document.head.append(meta);if(!db)return()=>meta.remove();let live=true;
  async function verify(s:Session|null){if(!live)return;setSession(s);if(!s){setStatus('login');return;}setStatus('checking');try{const ok=unwrap(await db!.rpc('is_admin'));if(live)setStatus(ok?'ready':'denied');}catch{if(live)setStatus('error');}}
  db.auth.getSession().then(({data})=>verify(data.session));const {data:{subscription}}=db.auth.onAuthStateChange((event,s)=>{if(event==='PASSWORD_RECOVERY')setRecovery(true);setTimeout(()=>verify(s),0);});return()=>{live=false;subscription.unsubscribe();meta.remove();};
 },[]);
 return <div className="admin-shell"><header className="admin-header"><a href="/" className="brand"><img src="/logo-white.png" alt="APB Detailing"/><span className="workspace-label">Owner workspace</span></a><div><a className="text-link" href="/" target="_blank" rel="noreferrer">View website ↗</a>{session&&<button className="button secondary small" onClick={async()=>{try{await disconnectPush();await db?.auth.signOut();}catch{alert('Could not disconnect phone alerts. Check your connection and try logging out again.');}}}>Log out</button>}</div></header>{status==='unconfigured'?<main className="login-panel"><h1>Owner workspace</h1><p>Account setup is still required. Follow the supplied setup guide to connect Supabase and authorise your owner account.</p></main>:status==='checking'?<main className="login-panel" role="status">Checking your access…</main>:status==='login'?<Login/>:status==='denied'?<main className="login-panel"><h1>Access restricted</h1><p>This account has not been authorised to manage APB Detailing.</p></main>:status==='error'?<main className="login-panel"><h1>Unable to connect</h1><p>The owner workspace is temporarily unavailable. Please refresh and try again. If the Supabase project is paused, restore it using the setup guide.</p><button className="button" onClick={()=>location.reload()}>Try again</button></main>:recovery?<ChangePassword done={()=>setRecovery(false)}/>:<Dashboard/>}</div>;
}
function Login(){const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[reset,setReset]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){const v=fields(event);setBusy(true);setNotice('');try{if(reset){unwrap(await db!.auth.resetPasswordForEmail(v.email,{redirectTo:`${location.origin}/admin`}));setNotice('If this email belongs to an account, a password reset link has been requested.');}else {const {error}=await db!.auth.signInWithPassword({email:v.email,password:v.password});if(error)throw error;}}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
 return <main className="login-panel"><p className="eyebrow">APB DETAILING</p><h1>{reset?'Reset password':'Welcome back.'}</h1><p className="muted">Your cars, services and enquiries, in one place.</p><form onSubmit={submit}><fieldset disabled={busy}><label>Email address<input type="email" name="email" autoComplete="username" required/></label>{!reset&&<label>Password<input type="password" name="password" autoComplete="current-password" required/></label>}<button className="button full">{busy?'Please wait…':reset?'Send reset link':'Log in'}</button></fieldset></form><button className="text-button" onClick={()=>{setReset(!reset);setNotice('');}}>{reset?'Back to login':'Forgot your password?'}</button><Notice message={notice}/></main>;
}
function ChangePassword({done}:{done:()=>void}){const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false);return <main className="login-panel"><h1>Choose a new password</h1><form onSubmit={async e=>{const v=fields(e);setBusy(true);try{const {error}=await db!.auth.updateUser({password:v.password});if(error)throw error;history.replaceState({},'', '/admin');done();}catch(err){setNotice(errorText(err));}finally{setBusy(false);}}}><label>New password<input type="password" name="password" autoComplete="new-password" minLength={12} required/></label><button className="button" disabled={busy}>Save password</button></form><Notice message={notice}/></main>;}
function Dashboard(){
 const [tab,setTab]=useState(location.hash==='#enquiries'?'enquiries':'showcase'),[entries,setEntries]=useState<Entry[]>([]),[services,setServices]=useState<Service[]>([]),[settings,setSettings]=useState(defaults),[enquiries,setEnquiries]=useState<Enquiry[]>([]),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
 async function refresh(){try{const [e,s,b,q]=await Promise.all([db!.from('showcase_entries').select('*,showcase_images(*)').order('display_order'),db!.from('services').select('*').order('display_order'),db!.from('business_settings').select('*').eq('id',1).single(),db!.from('enquiries').select('*').order('created_at',{ascending:false})]);setEntries(unwrap(e)||[]);setServices(unwrap(s)||[]);setSettings(unwrap(b));setEnquiries(unwrap(q)||[]);setNotice('');}catch(e){setNotice(errorText(e));}finally{setLoading(false);}}
 useEffect(()=>{void refresh();const route=()=>{if(location.hash==='#enquiries')setTab('enquiries');};window.addEventListener('hashchange',route);return()=>window.removeEventListener('hashchange',route);},[]);
 useEffect(()=>{let alive=true;async function poll(){if(document.visibilityState!=='visible')return;try{const q=await db!.from('enquiries').select('*').order('created_at',{ascending:false});if(alive&&!q.error)setEnquiries(q.data||[]);}catch{/* Keep the last confirmed inbox during a connection failure. */}}const timer=setInterval(poll,30000);document.addEventListener('visibilitychange',poll);return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',poll);};},[]);
 const tabs=[['showcase','Manage showcase'],['services','Manage services'],['pricing','Manage pricing'],['enquiries',`Messages${enquiries.filter(e=>!e.read_at).length?` (${enquiries.filter(e=>!e.read_at).length})`:''}`],['settings','Business settings']];
 return <div className="admin-layout"><aside><p className="eyebrow">YOUR WEBSITE</p><nav aria-label="Owner sections">{tabs.map(([id,name])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);history.replaceState(null,'',id==='enquiries'?'/admin#enquiries':'/admin');}}>{name}</button>)}</nav><p className="fine">Changes are saved to your website.<br/>Draft vehicles stay private.</p></aside><main className="admin-main"><PushSettings/><Notice message={notice}/>{notice&&<button className="button secondary" onClick={refresh}>Retry connection</button>}{loading?<p role="status">Loading your content…</p>:tab==='showcase'?<Showcase entries={entries} services={services} refresh={refresh}/>:tab==='services'?<ServiceManager services={services} refresh={refresh}/>:tab==='pricing'?<Pricing services={services} settings={settings} refresh={refresh}/>:tab==='enquiries'?<Inbox enquiries={enquiries} refresh={refresh}/>:<Business settings={settings} refresh={refresh}/>}</main></div>;
}
function Showcase({entries,services,refresh}:{entries:Entry[];services:Service[];refresh:()=>Promise<void>}){
 const [selected,setSelected]=useState<string|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const entry=entries.find(e=>e.id===selected);
 if(selected==='new'||entry)return <VehicleEditor key={entry?.id||'new'} entry={entry} services={services} refresh={refresh} onBack={()=>setSelected(null)} onCreated={setSelected}/>;
 return <><div className="admin-title"><div><p className="eyebrow">VEHICLE PORTFOLIO</p><h1>Manage showcase</h1><p className="muted">Add a car, upload photographs, then publish.</p></div><button className="button" onClick={()=>setSelected('new')}>+ Add car</button></div>{!entries.length&&<div className="admin-card"><h2>Your first car starts here.</h2><p className="muted">Create a draft and add up to 10 photos. Only publish work you have permission to share.</p></div>}<div className="admin-vehicle-list">{entries.map(e=><article className="admin-card" key={e.id}><div><span className={`tag ${e.published?'published':''}`}>{e.deleting?'Deletion needs retry':e.published?'Published':'Draft'}</span><h2>{e.name}</h2><p className="muted">{e.showcase_images.length} of 10 photographs uploaded</p></div><div className="actions"><button className="button secondary" onClick={()=>setSelected(e.id)}>Edit car</button><button className="text-button danger" disabled={busy} onClick={async()=>{if(!confirm(`Delete ${e.name} and all its photographs? This cannot be undone.`))return;setBusy(true);try{await api('vehicles',{id:e.id},'DELETE');await refresh();setNotice('Vehicle and photographs deleted.');}catch(err){setNotice(errorText(err)+' You can retry deletion.');}finally{setBusy(false);}}}>Delete</button></div></article>)}</div><Notice message={notice}/></>;
}
function VehicleEditor({entry,services,refresh,onBack,onCreated}:{entry?:Entry;services:Service[];refresh:()=>Promise<void>;onBack:()=>void;onCreated:(id:string)=>void}){
 const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const value={name:String(f.get('name')||'').trim(),year:f.get('year')?Number(f.get('year')):null,description:String(f.get('description')||''),service_ids:f.getAll('service_ids'),featured:f.get('featured')==='on',display_order:Number(f.get('display_order')||0)};
 if(entry)unwrap(await db!.from('showcase_entries').update(value).eq('id',entry.id));else{const created=unwrap(await db!.from('showcase_entries').insert(value).select('id').single());if(!created)throw new Error('The vehicle could not be confirmed. Refresh the showcase before trying again.');await refresh();onCreated(created.id);return;}await refresh();setNotice('Vehicle details saved.');}catch(err){setNotice(errorText(err));}finally{setBusy(false);}}
 return <><button className="text-button" onClick={onBack}>← All vehicles</button><div className="admin-title"><h1>{entry?entry.name:'Add a car'}</h1>{entry&&<span className={`tag ${entry.published?'published':''}`}>{entry.published?'Published':'Draft'}</span>}</div><form className="admin-card" onSubmit={save}><fieldset disabled={busy||entry?.deleting}><div className="form-grid"><label>Vehicle make and model<input name="name" defaultValue={entry?.name} maxLength={150} required placeholder="e.g. BMW 3 Series"/></label><label>Year (optional)<input name="year" type="number" min={1900} max={2100} defaultValue={entry?.year||''}/></label></div><label>Work completed<textarea name="description" rows={4} maxLength={5000} defaultValue={entry?.description}/></label><fieldset className="service-checks"><legend>Services performed</legend>{services.map(s=><label className="check-label" key={s.id}><input type="checkbox" name="service_ids" value={s.id} defaultChecked={entry?.service_ids.includes(s.id)}/>{s.name}{!s.enabled?' (hidden service)':''}</label>)}</fieldset><div className="form-grid"><label>Display order<input name="display_order" type="number" defaultValue={entry?.display_order||0}/></label><Check name="featured" checked={entry?.featured}>Feature this vehicle on the homepage</Check></div><button className="button">{busy?'Saving…':entry?'Save details':'Save car & add photos'}</button></fieldset></form><Notice message={notice}/>{entry&&<><PhotoManager entry={entry} refresh={refresh}/><div className="admin-card publish-panel"><h2>{entry.published?'This car is on your website.':'Ready to share?'}</h2><p className="muted">Check your description, photographs and customer permission before publishing. Remove or obscure number plates and faces when needed.</p><button className="button" disabled={busy||entry.deleting||(!entry.published&&!entry.showcase_images.some(p=>p.status==='ready'))} onClick={async()=>{setBusy(true);try{unwrap(await db!.from('showcase_entries').update({published:!entry.published}).eq('id',entry.id));await refresh();setNotice(entry.published?'Vehicle unpublished.':'Vehicle published.');}catch(err){setNotice(errorText(err));}finally{setBusy(false);}}}>{entry.published?'Unpublish vehicle':'Publish vehicle'}</button>{entry.published&&<a className="text-link" href={`/work/${entry.id}`} target="_blank" rel="noreferrer">View showcase ↗</a>}</div></>}</>;
}
function PhotoManager({entry,refresh}:{entry:Entry;refresh:()=>Promise<void>}){
 const [urls,setUrls]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[progress,setProgress]=useState({done:0,total:0});const photos=[...entry.showcase_images].sort((a,b)=>a.display_order-b.display_order);
 useEffect(()=>{let active=true;Promise.all(photos.filter(p=>p.status==='ready').map(async p=>{const {data}=await db!.storage.from('apb-media').createSignedUrl(p.path,300);return [p.id,data?.signedUrl||''];})).then(pairs=>{if(active)setUrls(Object.fromEntries(pairs));});return()=>{active=false;};},[entry.showcase_images]);
 async function upload(files:File[]){if(!files?.length)return;if(files.length+photos.length>10){setNotice(`You can add ${10-photos.length} more photographs. A before-and-after pair uses two slots.`);return;}setBusy(true);setProgress({done:0,total:files.length});try{for(let i=0;i<files.length;i++){const blob=await compressPhoto(files[i],m=>setNotice(`Photo ${i+1} of ${files.length}: ${m}`));const form=new FormData();form.set('photo',blob,'photo.webp');form.set('entry_id',entry.id);setNotice(`Uploading photo ${i+1} of ${files.length}…`);await api('photos',form);setProgress({done:i+1,total:files.length});}setNotice('Photographs uploaded. Your original files are unchanged.');}catch(e){setNotice(errorText(e));}finally{await refresh();setBusy(false);}}
 async function update(p:Photo,values:Record<string,unknown>){setBusy(true);try{unwrap(await db!.from('showcase_images').update(values).eq('id',p.id));await refresh();setNotice('Photograph updated.');}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
 async function move(index:number,delta:number){setBusy(true);try{const reordered=[...photos];[reordered[index],reordered[index+delta]]=[reordered[index+delta],reordered[index]];for(let i=0;i<reordered.length;i++)unwrap(await db!.from('showcase_images').update({display_order:i}).eq('id',reordered[i].id));await refresh();}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
 return <section className="admin-card"><div className="admin-title"><div><h2>Photographs</h2><p>{photos.length} of 10 photographs uploaded</p></div><label className={`button file-button ${busy||photos.length>=10||entry.deleting?'disabled':''}`}>+ Upload photos<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple disabled={busy||photos.length>=10||entry.deleting} onChange={e=>{void upload(Array.from(e.target.files||[]));e.target.value='';}}/></label></div><p className="fine">Photos are resized and compressed before upload. Before and after photos each use one slot. Select up to {10-photos.length} more.</p>{busy&&progress.total>0&&<progress aria-label="Photographs uploaded" max={progress.total} value={progress.done}/>}<Notice message={notice}/><div className="photo-grid">{photos.map((p,i)=><article key={p.id} className="photo-editor">{urls[p.id]?<img src={urls[p.id]} alt={p.alt||entry.name}/>:<div className="pending-photo">{p.status==='pending'?'Upload incomplete — delete to free this slot.':'Loading photograph…'}</div>}<fieldset disabled={busy||entry.deleting}><label>Photo description<input defaultValue={p.alt} maxLength={300} onBlur={e=>{if(e.target.value!==p.alt)void update(p,{alt:e.target.value});}}/></label><label>Comparison role<select value={p.role} onChange={e=>void update(p,{role:e.target.value})}><option value="general">General photograph</option><option value="before" disabled={photos.some(q=>q.id!==p.id&&q.role==='before')}>Before</option><option value="after" disabled={photos.some(q=>q.id!==p.id&&q.role==='after')}>After</option></select></label><button className="text-button" disabled={p.status!=='ready'} onClick={async()=>{setBusy(true);try{unwrap(await db!.from('showcase_entries').update({featured_image_id:p.id}).eq('id',entry.id));await refresh();}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}}>{p.id===entry.featured_image_id?'✓ Cover photograph':'Use as cover'}</button><div className="photo-actions"><button aria-label={`Move photograph ${i+1} earlier`} disabled={i===0} onClick={()=>void move(i,-1)}>↑</button><button aria-label={`Move photograph ${i+1} later`} disabled={i===photos.length-1} onClick={()=>void move(i,1)}>↓</button><button className="danger" onClick={async()=>{if(!confirm('Delete this photograph? It will also be removed from storage.'))return;setBusy(true);try{await api('photos',{id:p.id},'DELETE');await refresh();setNotice('Photograph deleted.');}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}}>Delete</button></div></fieldset></article>)}</div></section>;
}
function ServiceManager({services,refresh}:{services:Service[];refresh:()=>Promise<void>}){return <><div className="admin-title"><div><h1>Manage services</h1><p className="muted">Update descriptions and choose what customers see.</p></div></div>{services.map(s=><ServiceEditor key={s.id} service={s} refresh={refresh}/>)}</>;}
function ServiceEditor({service:s,refresh}:{service:Service;refresh:()=>Promise<void>}){const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[image,setImage]=useState('');useEffect(()=>{let live=true;if(s.image_path)db!.storage.from('apb-media').createSignedUrl(s.image_path,300).then(({data})=>{if(live)setImage(data?.signedUrl||'');});else setImage('');return()=>{live=false;};},[s.image_path]);
 return <form className="admin-card" onSubmit={async e=>{const v=fields(e);setBusy(true);try{unwrap(await db!.from('services').update({name:v.name.trim(),description:v.description,enabled:v.enabled==='on',display_order:Number(v.display_order)}).eq('id',s.id));await refresh();setNotice('Service saved.');}catch(err){setNotice(errorText(err));}finally{setBusy(false);}}}><fieldset disabled={busy}><div className="form-grid"><label>Service name<input name="name" defaultValue={s.name} maxLength={100} required/></label><label>Display order<input name="display_order" type="number" defaultValue={s.display_order}/></label></div><label>Description<textarea name="description" rows={3} defaultValue={s.description} maxLength={2000}/></label><Check name="enabled" checked={s.enabled}>Show this service on the website</Check>{image&&<img className="service-admin-image" src={image} alt={s.name}/>}<div className="actions"><button className="button">Save service</button><label className="button secondary file-button">{s.image_path?'Replace photo':'Add photo'}<input type="file" accept="image/*" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);try{const blob=await compressPhoto(file,setNotice);const form=new FormData();form.set('photo',blob,'service.webp');form.set('service_id',s.id);await api('photos',form);await refresh();const {data}=await db!.storage.from('apb-media').createSignedUrl(`services/${s.id}.webp`,300);setImage(data?.signedUrl||'');setNotice('Service photograph saved.');}catch(err){setNotice(errorText(err));}finally{setBusy(false);}}}/></label>{s.image_path&&<button className="text-button danger" type="button" onClick={async()=>{setBusy(true);try{await api('photos',{service_id:s.id},'DELETE');await refresh();setNotice('Service photograph removed.');}catch(err){setNotice(errorText(err));}finally{setBusy(false);}}}>Remove photo</button>}</div></fieldset><Notice message={notice}/></form>;
}
function Pricing({services,settings,refresh}:{services:Service[];settings:Settings;refresh:()=>Promise<void>}){const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false);return <><h1>Manage pricing</h1><p className="muted">Leave prices hidden until your price list is confirmed.</p><div className="admin-card"><label className="check-label"><input type="checkbox" checked={settings.show_prices} disabled={busy} onChange={async e=>{setBusy(true);try{unwrap(await db!.from('business_settings').update({show_prices:e.target.checked}).eq('id',1));await refresh();}catch(err){setNotice(errorText(err));}finally{setBusy(false);}}}/>Show prices publicly</label><p className="fine">When off, every service shows “Price on request”.</p></div>{services.map(s=><PriceEditor key={s.id} service={s} refresh={refresh}/>)}<Notice message={notice}/></>;}
function PriceEditor({service:s,refresh}:{service:Service;refresh:()=>Promise<void>}){const [mode,setMode]=useState(s.price_mode),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);return <form className="admin-card" onSubmit={async e=>{const v=fields(e);setBusy(true);try{unwrap(await db!.from('services').update({price_mode:mode,price:mode==='request'?null:Number(v.price),show_price:v.show_price==='on',pricing_description:v.pricing_description}).eq('id',s.id));await refresh();setNotice('Pricing saved.');}catch(err){setNotice(errorText(err));}finally{setBusy(false);}}}><h2>{s.name}</h2><fieldset disabled={busy}><div className="form-grid"><label>Pricing type<select value={mode} onChange={e=>setMode(e.target.value as Service['price_mode'])}><option value="request">Price on request</option><option value="fixed">Fixed price</option><option value="from">Starting price</option></select></label>{mode!=='request'&&<label>Price (£)<input name="price" type="number" min="0" max="99999999" step="0.01" required defaultValue={s.price??''}/></label>}</div><label>Pricing note (optional)<input name="pricing_description" maxLength={500} defaultValue={s.pricing_description}/></label><Check name="show_price" checked={s.show_price}>Show this service’s price when public pricing is enabled</Check><button className="button">Save pricing</button></fieldset><Notice message={notice}/></form>;}
function Inbox({enquiries,refresh}:{enquiries:Enquiry[];refresh:()=>Promise<void>}){
 const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[unreadOnly,setUnreadOnly]=useState(false);
 const unread=enquiries.filter(q=>!q.read_at).length,visible=enquiries.filter(q=>!unreadOnly||!q.read_at);
 async function change(q:Enquiry,remove=false){if(remove&&!confirm('Permanently delete this enquiry and its contact details? This cannot be undone.'))return;setBusy(true);setNotice('');try{const result=remove?await db!.from('enquiries').delete().eq('id',q.id).select('id'):await db!.from('enquiries').update({read_at:q.read_at?null:new Date().toISOString()}).eq('id',q.id).select('id');const rows=unwrap(result);if(!rows?.length)throw new Error('This enquiry is no longer available, or your access has changed.');await refresh();setNotice(remove?'Enquiry deleted.':q.read_at?'Marked as unread.':'Marked as read.');}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
 return <><div className="admin-title"><div><p className="eyebrow">CUSTOMER ENQUIRIES</p><h1>Message centre</h1><p className="muted" role="status">{unread} unread · {enquiries.length} total</p></div><button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await refresh();}finally{setBusy(false);}}}>Refresh messages</button></div><p className="fine">Website enquiries appear here. Contact the customer using their details below. Messages refresh every 30 seconds while this page is visible.</p><label className="check-label"><input type="checkbox" checked={unreadOnly} onChange={e=>setUnreadOnly(e.target.checked)}/>Show unread only</label><Notice message={notice}/>{!visible.length&&<div className="admin-card"><h2>{unreadOnly?'All caught up.':'No enquiries yet.'}</h2><p>{unreadOnly?'There are no unread enquiries.':'New website enquiries will appear here.'}</p></div>}{visible.map(q=><article className="admin-card enquiry" key={q.id} style={!q.read_at?{borderLeft:'4px solid #79cfed'}:undefined}><div className="admin-title"><div><span className="tag">{q.read_at?'Read':'Unread'}</span><p className="fine">{new Date(q.created_at).toLocaleString('en-GB')}</p><h2>{q.name}</h2></div><button className="button secondary small" disabled={busy} onClick={()=>void change(q)}>{q.read_at?'Mark unread':'Mark as read'}</button></div><div className="enquiry-contacts"><a href={`mailto:${q.email}`}>{q.email}</a><a href={`tel:${q.telephone.replace(/[^+\d]/g,'')}`}>{q.telephone}</a></div><p><strong>{q.service_name}</strong>{q.vehicle&&` · ${q.vehicle}`}</p><p className="pre-line">{q.message}</p><button className="text-button danger" disabled={busy} onClick={()=>void change(q,true)}>Delete enquiry</button></article>)}</>;
}
function Business({settings:s,refresh}:{settings:Settings;refresh:()=>Promise<void>}){const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false);return <><h1>Business settings</h1><p className="muted">Leave anything unconfirmed empty. Only publish your address when you’re ready.</p><form className="admin-card" onSubmit={async e=>{const v=fields(e);setBusy(true);try{if(v.telephone&&!phone(v.telephone))throw new Error('Enter a valid telephone number, including +44 for the UK.');if(v.whatsapp&&!phone(v.whatsapp))throw new Error('Enter a valid WhatsApp number, including +44 for the UK.');if((v.facebook_url&&!safeSocial(v.facebook_url))||(v.instagram_url&&!safeSocial(v.instagram_url)))throw new Error('Social links must start with https://');unwrap(await db!.from('business_settings').update({...v,show_address:v.show_address==='on'}).eq('id',1));await refresh();setNotice('Business settings saved.');}catch(err){setNotice(errorText(err));}finally{setBusy(false);}}}><fieldset disabled={busy}><div className="form-grid"><label>Telephone<input name="telephone" type="tel" defaultValue={s.telephone} maxLength={30} placeholder="+44…"/></label><label>WhatsApp number<input name="whatsapp" type="tel" defaultValue={s.whatsapp} maxLength={30} placeholder="+44…"/></label><label>Public email address<input name="email" type="email" defaultValue={s.email} maxLength={254}/></label><label>Service area<input name="service_area" defaultValue={s.service_area} maxLength={150} required/></label></div><label>Business address<textarea name="address" rows={3} defaultValue={s.address} maxLength={1000}/></label><Check name="show_address" checked={s.show_address}>Publish this address on the website</Check><label>Opening hours<textarea name="opening_hours" rows={3} defaultValue={s.opening_hours} maxLength={1000} placeholder="Leave blank until confirmed"/></label><div className="form-grid"><label>Facebook link<input name="facebook_url" type="url" defaultValue={s.facebook_url}/></label><label>Instagram link<input name="instagram_url" type="url" defaultValue={s.instagram_url}/></label></div><button className="button">Save business settings</button></fieldset><Notice message={notice}/></form></>;}
