import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {Service} from './data';
type Turnstile={render:(element:HTMLElement,options:Record<string,unknown>)=>string;remove:(id:string)=>void;reset:(id:string)=>void};
declare global{interface Window{turnstile?:Turnstile;}}
export function ContactForm({services}:{services:Service[]}){
 const [token,setToken]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[service,setService]=useState(new URLSearchParams(location.search).get('service')||'');
 const ref=useRef<HTMLDivElement>(null),widget=useRef<string|undefined>(undefined),form=useRef<HTMLFormElement>(null);
 const configured=!!(import.meta.env.VITE_SUPABASE_URL&&import.meta.env.VITE_TURNSTILE_SITE_KEY);
 useEffect(()=>{if(!configured||sent)return;let disposed=false;const render=()=>{if(!disposed&&ref.current&&window.turnstile&&widget.current===undefined)widget.current=window.turnstile.render(ref.current,{sitekey:import.meta.env.VITE_TURNSTILE_SITE_KEY,action:'quote',theme:'dark',callback:(t:string)=>setToken(t),'expired-callback':()=>setToken(''),'error-callback':()=>{setToken('');setNotice('The security check couldn’t load. Please refresh or contact us directly.');}});};
 let script=document.querySelector<HTMLScriptElement>('#turnstile-script');if(!script){script=document.createElement('script');script.id='turnstile-script';script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;document.head.append(script);}script.addEventListener('load',render);render();
 return()=>{disposed=true;script?.removeEventListener('load',render);if(widget.current!==undefined){window.turnstile?.remove(widget.current);widget.current=undefined;}};
 },[configured,sent]);
 async function submit(e:FormEvent){e.preventDefault();if(!configured||!token)return;setBusy(true);setNotice('');const fields=Object.fromEntries(new FormData(form.current!).entries());
 try{const response=await fetch('/api/enquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,service_id:service,privacy_acknowledged:fields.privacy_acknowledged==='on',token})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Your enquiry could not be sent. Please try again.');setSent(true);form.current?.reset();}
 catch(e){setNotice(e instanceof Error?e.message:'Your enquiry could not be sent. Please try again.');}finally{setBusy(false);setToken('');if(widget.current)window.turnstile?.reset(widget.current);}}
 if(sent)return <div className="success-panel" role="status"><span aria-hidden="true">✓</span><h3>Thanks. Your enquiry is with us.</h3><p>APB Detailing will contact you using the details you provided.</p><button className="button secondary" onClick={()=>setSent(false)}>Send another enquiry</button></div>;
 return <form ref={form} onSubmit={submit}><h3>Request a quote</h3><p className="muted">A few details about you and your car.</p>{!configured&&<p className="notice">Online enquiries will open soon. Please check back shortly.</p>}<fieldset disabled={busy||!configured}><div className="form-grid"><label>Your name<input name="name" autoComplete="name" required maxLength={100}/></label><label>Email address<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Telephone<input name="telephone" type="tel" autoComplete="tel" required minLength={7} maxLength={30}/></label><label>Vehicle make / model <span className="optional">(optional)</span><input name="vehicle" defaultValue={new URLSearchParams(location.search).get('vehicle')||''} maxLength={150} placeholder="e.g. Volkswagen Golf"/></label></div><label>Service of interest<select name="service_id" value={service} onChange={e=>setService(e.target.value)} required><option value="">Choose a service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Tell us about your car<textarea name="message" rows={4} required minLength={10} maxLength={5000} placeholder="What would you like us to help with?"/></label><div className="honeypot" aria-hidden="true"><label>Leave empty<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="check-label"><input type="checkbox" name="privacy_acknowledged" required/><span>I’ve read the <a href="/privacy" target="_blank" rel="noreferrer">privacy information</a> and understand APB Detailing will use my details to respond to this enquiry.</span></label><div ref={ref} className="turnstile"/><button className="button full" disabled={busy||!token}>{busy?'Sending…':'Send quote enquiry'} <span aria-hidden="true">↗</span></button></fieldset>{notice&&<p className="notice error" role="alert">{notice}</p>}<p className="fine">An enquiry doesn’t book an appointment. We’ll discuss the details with you.</p></form>;
}
