import {useEffect,useState,type ReactNode} from 'react';
import type {Entry,Service,Settings} from './data';
import {whatsapp} from './data';
import {media} from './client';
export function PageShell({children}:{children:ReactNode}){return <><a className="skip" href="#main">Skip to content</a><header className="header"><a className="brand" href="/"><img src="/logo-white.png" alt="APB Detailing"/></a><nav><a href="/#work">Our work</a><a className="button small" href="/#quote">Get a quote ↗</a></nav></header><main id="main" className="section">{children}</main><footer className="footer"><a href="/">APB Detailing · Selby</a><a href="/privacy">Privacy</a></footer></>;}
export function Privacy({settings}:{settings:Settings}){return <PageShell><article className="prose"><p className="eyebrow">YOUR INFORMATION</p><h1>Privacy</h1><p>APB Detailing uses the details you send through this website to respond to your enquiry and discuss the services you request.</p><h2>What we collect</h2><p>Your name, email address, telephone number, optional vehicle details, chosen service and message. Please don’t include payment information or other sensitive information.</p><h2>How we use it</h2><p>We use enquiry details to take steps at your request before providing a service, and to manage correspondence. They are accessible only to authorised APB Detailing administrators. The form acknowledgement is not consent to marketing.</p><h2>Website providers</h2><p>Cloudflare hosts the website and protects the form with Turnstile. Supabase stores enquiries, website content and owner sign-in information. These providers process information on our behalf; processing locations depend on the configured hosting region and their safeguards.</p><p>For abuse prevention, the form processes your IP address and a short-lived hashed rate-limit identifier. The owner’s login uses local browser storage to maintain the sign-in session. This website does not add advertising or analytics trackers.</p><h2>Keeping and deleting information</h2><p>APB Detailing should review and remove enquiries when they are no longer needed to respond to you or meet applicable obligations. You can ask about, correct or request deletion of your information by contacting APB Detailing{settings.email?<> at <a href={`mailto:${settings.email}`}>{settings.email}</a></>:<> using its published contact details</>}.</p><h2>Photographs and WhatsApp</h2><p>Customer vehicle photographs are published only after the owner confirms permission and checks for personal details such as number plates or faces. WhatsApp is optional; if you use it, its own privacy terms also apply.</p><p>You can raise a concern with the UK Information Commissioner’s Office at <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noreferrer">ico.org.uk</a>.</p></article></PageShell>;}
export function VehiclePage({entry,services,settings,loading,error}:{entry?:Entry;services:Service[];settings:Settings;loading:boolean;error:boolean}){
 const [position,setPosition]=useState(50);const photos=entry?.showcase_images.filter(p=>p.status==='ready').sort((a,b)=>a.display_order-b.display_order)||[];const before=photos.find(p=>p.role==='before'),after=photos.find(p=>p.role==='after');
 useEffect(()=>{if(entry){document.title=`${entry.name} | APB Detailing, Selby`;document.querySelector('meta[name="description"]')?.setAttribute('content',entry.description.slice(0,160));}},[entry]);
 if(!entry)return <PageShell><h1>{loading?'Loading vehicle…':error?'This vehicle couldn’t load.':'Vehicle not found.'}</h1><p>{error?'Please try again shortly.':'This showcase may not be published yet.'}</p><a className="button" href="/#work">Back to our work</a></PageShell>;
 const featured=photos.find(p=>p.id===entry.featured_image_id)||photos[0],wa=whatsapp(settings.whatsapp,`I'm interested in work like the ${entry.name} showcase.`);
 return <PageShell><a className="text-link" href="/#work">← Back to our work</a><div className="detail-heading"><div><p className="eyebrow">THE VEHICLE PORTFOLIO {entry.year&&`/ ${entry.year}`}</p><h1>{entry.name}</h1><div className="tags">{entry.service_ids.map(id=>services.find(s=>s.id===id)).filter(Boolean).map(s=><span key={s!.id}>{s!.name}</span>)}</div></div><a className="button" href={`/?vehicle=${encodeURIComponent(entry.name)}#quote`}>Enquire about your car ↗</a></div>{featured&&<img className="detail-cover" src={media(featured.path)} alt={featured.alt||entry.name}/>}<p className="detail-description pre-line">{entry.description}</p>{before&&after&&<section className="comparison-section"><p className="eyebrow">BEFORE / AFTER</p><h2>See the difference.</h2><div className="comparison"><img src={media(after.path)} alt={after.alt||`${entry.name} after detailing`}/><img className="comparison-before" src={media(before.path)} alt={before.alt||`${entry.name} before detailing`} style={{clipPath:`inset(0 ${100-position}% 0 0)`}}/><span className="comparison-label left">Before</span><span className="comparison-label right">After</span><div className="comparison-line" style={{left:`${position}%`}}><span>↔</span></div><input aria-label="Compare before and after photographs" type="range" min="0" max="100" value={position} onChange={e=>setPosition(Number(e.target.value))}/></div><p className="fine">Drag across the image, or use the arrow keys to compare.</p></section>}<div className="detail-gallery">{photos.filter(p=>p.id!==featured?.id).map(p=><figure key={p.id}><img src={media(p.path)} alt={p.alt||`${entry.name} detailing photograph`} loading="lazy"/>{p.alt&&<figcaption>{p.alt}</figcaption>}</figure>)}</div><div className="detail-cta"><h2>A finish for your car.</h2><p className="muted">Contact us for a personalised quote.</p><div className="actions"><a className="button" href="/#quote">Get a quote ↗</a>{wa&&<a className="text-link" href={wa} target="_blank" rel="noreferrer">Ask on WhatsApp ↗</a>}</div></div></PageShell>;
}
export function useSeo(settings:Settings){useEffect(()=>{
 const origin=import.meta.env.VITE_SITE_URL?.replace(/\/$/,'');if(origin){let link=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.append(link);}link.href=origin+location.pathname;}
 const structured={ '@context':'https://schema.org','@type':'AutomotiveBusiness',name:'APB Detailing',areaServed:settings.service_area,...(origin?{url:origin}:{}),...(settings.telephone?{telephone:settings.telephone}:{}),...(settings.show_address&&settings.address?{address:settings.address}:{})};
 const script=document.createElement('script');script.type='application/ld+json';script.textContent=JSON.stringify(structured);document.head.append(script);return()=>script.remove();
 },[settings]);}
